# Generated by Django 4.0.5 on 2022-06-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teilnehmer',
            fields=[
                ('edv_nummer', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('vname', models.CharField(max_length=255)),
                ('nname', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('plz', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.orte')),
            ],
        ),
    ]
