# Generated by Django 4.0.5 on 2022-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teilnehmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Az_zustaendigkeit',
            fields=[
                ('kuerzel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('dauer', models.IntegerField(verbose_name='Dauer in Monaten')),
            ],
        ),
    ]
