# Generated by Django 4.0.5 on 2022-06-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_baz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('reaktionszeit', models.IntegerField(verbose_name='Reaktionszeit in Tagen')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.betrieb')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.teilnehmer')),
            ],
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertung', models.IntegerField(verbose_name='Schulnoten 7 erfolglos')),
                ('bemerkung', models.TextField()),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.teilnehmer')),
            ],
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=255)),
                ('telefon_zentrale', models.CharField(blank=True, max_length=255)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.betrieb')),
                ('plz', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.orte')),
            ],
        ),
        migrations.CreateModel(
            name='Praktikum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateField()),
                ('ende', models.DateField()),
                ('ausbildungszweig', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.az_zustaendigkeit')),
                ('bewerbung', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.bewerbung')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.betrieb')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.teilnehmer')),
            ],
        ),
        migrations.CreateModel(
            name='BewertungPraktikum',
            fields=[
                ('bewertung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.bewertung')),
                ('praktikum', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.praktikum')),
            ],
            bases=('app1.bewertung',),
        ),
        migrations.CreateModel(
            name='BewertungBetrieb',
            fields=[
                ('bewertung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.bewertung')),
                ('betrieb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app1.betrieb')),
            ],
            bases=('app1.bewertung',),
        ),
    ]
